branch-protection:
  orgs:
    jenkins-x-charts:
      required_status_checks:
        contexts: ["tekton"]
    jenkins-x-apps:
      required_status_checks:
        contexts: ["tekton"]
    jenkins-x:
      repos:
        environment-tekton-mole-dev:
          required_status_checks:
            contexts:
            - promotion-build
        environment-tekton-mole-production:
          required_status_checks:
            contexts:
            - promotion-build
        environment-tekton-mole-staging:
          required_status_checks:
            contexts:
            - promotion-build
        jx:
          required_status_checks:
            contexts:
              ["bdd","integration","lint"]
        jenkins-x-builders-base-image:
          required_status_checks:
            contexts: ["tekton"]
  protect-tested-repos: true
deck:
  spyglass: {}
gerrit: {}
owners_dir_blacklist:
  default: null
  repos: null
plank:
  report_template: '{{if eq .Spec.Type "presubmit"}}[View all Builds for this Pull Request](https://core.jx.tekton.rawlings.it/teams/{{.Spec.Namespace}}/projects/browse/{{.Spec.Refs.Repo}}/PR-{{(index .Spec.Refs.Pulls 0).Number}}) {{else if eq .Spec.Type "batch"}} Run `jx get build log --owner {{.Spec.Refs.Org}} --repo {{.Spec.Refs.Repo}} --branch batch` whilst connected to the cluster. UI support coming soon. {{end}}'
pod_namespace: jx
postsubmits:
  jenkins-x/environment-tekton-mole-dev:
  - agent: tekton
    branches:
    - master
    context: ""
    name: promotion
  jenkins-x/environment-tekton-mole-production:
  - agent: tekton
    branches:
    - master
    context: ""
    name: promotion
  jenkins-x/environment-tekton-mole-staging:
  - agent: tekton
    branches:
    - master
    context: ""
    name: promotion
  jenkins-x-charts/prow:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jx:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-builders-base-image:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
presubmits:
  jenkins-x/environment-tekton-mole-dev:
  - agent: tekton
    always_run: true
    context: promotion-build
    name: promotion-build
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
  jenkins-x/environment-tekton-mole-production:
  - agent: tekton
    always_run: true
    context: promotion-build
    name: promotion-build
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
  jenkins-x/environment-tekton-mole-staging:
  - agent: tekton
    always_run: true
    context: promotion-build
    name: promotion-build
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
  jenkins-x-charts/prow:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jx:
  - agent: tekton
    always_run: true
    context: bdd
    name: bdd
    rerun_command: /test bdd
    trigger: (?m)^/test( all| bdd),?(s+|$)
  - agent: tekton
    always_run: true
    context: integration
    name: integration
    rerun_command: /test integration
    trigger: (?m)^/test( all| integration),?(s+|$)
  - agent: tekton
    always_run: true
    context: lint
    name: lint
    rerun_command: /test lint
    trigger: (?m)^/test( all| lint),?(s+|$)
  jenkins-x/jenkins-x-builders-base-image:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
prowjob_namespace: jx
push_gateway: {}
sinker: {}
tide:
  context_options:
    from-branch-protection: true
    required-if-present-contexts: null
    skip-unknown-contexts: false
  queries:
  - labels:
    - updatebot
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x-charts/prow
    - jenkins-x/jenkins-x-builders-base-image
    - jenkins-x/jx
  - labels:
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x-charts/prow
    - jenkins-x/jenkins-x-builders-base-image
    - jenkins-x/jx
  - missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x/environment-tekton-mole-production
    - jenkins-x/environment-tekton-mole-staging
    - jenkins-x/environment-tekton-mole-dev
  target_url: https://deck.infra.jrawlings.co.uk