branch-protection:
  orgs:
    jenkins-x-charts:
      required_status_checks:
        contexts: ["tekton"]
    jenkins-x-apps:
      required_status_checks:
        contexts: ["tekton"]
    jenkins-x:
      repos:
        environment-tekton-mole-dev:
          required_status_checks:
            contexts:
            - promotion-build
        environment-tekton-mole-production:
          required_status_checks:
            contexts:
            - promotion-build
        environment-tekton-mole-staging:
          required_status_checks:
            contexts:
            - promotion-build
        jx:
          required_status_checks:
            contexts:
              ["bdd","integration","lint"]
        jx-docs:
          required_status_checks:
            contexts: ["tekton"]
        jx-tutorial:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-builders-base-image:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-builders-base:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-builders:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-serverless-filerunner:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-serverless:
          required_status_checks:
            contexts: ["tekton"]
        homebrew-jx:
          required_status_checks:
            contexts: ["tekton"]
        dev-env:
          required_status_checks:
            contexts: ["tekton"]
        updatebot:
          required_status_checks:
            contexts: ["tekton"]
        ext-java-code-quality:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-image:
          required_status_checks:
            contexts: ["tekton"]
  protect-tested-repos: true
deck:
  spyglass: {}
gerrit: {}
owners_dir_blacklist:
  default: null
  repos: null
plank:
  report_template: '{{if eq .Spec.Type "presubmit"}}[View all Builds for this Pull Request](https://core.infra.jrawlings.co.uk/teams/{{.Spec.Namespace}}/projects/browse/{{.Spec.Refs.Repo}}/PR-{{(index .Spec.Refs.Pulls 0).Number}}) {{else if eq .Spec.Type "batch"}} Run `jx get build log --owner {{.Spec.Refs.Org}} --repo {{.Spec.Refs.Repo}} --branch batch` whilst connected to the cluster. UI support coming soon. {{end}}'
  job_url_template: '{{if eq .Spec.Type "presubmit"}}[View Build Log](https://core.infra.jrawlings.co.uk/teams/{{.Spec.Namespace}}/projects/browse/{{.Spec.Refs.Repo}}/PR-{{(index .Spec.Refs.Pulls 0).Number}}/{{.Status.BuildID}}) {{else if eq .Spec.Type "batch"}} Run `jx get build log --owner {{.Spec.Refs.Org}} --repo {{.Spec.Refs.Repo}} --branch batch --build {{.Status.BuildID}}` whilst connected to the cluster. UI support coming soon. {{end}}'
pod_namespace: jx
postsubmits:
  jenkins-x/environment-tekton-mole-dev:
  - agent: tekton
    branches:
    - master
    context: ""
    name: promotion
  jenkins-x/environment-tekton-mole-production:
  - agent: tekton
    branches:
    - master
    context: ""
    name: promotion
  jenkins-x/environment-tekton-mole-staging:
  - agent: tekton
    branches:
    - master
    context: ""
    name: promotion
  jenkins-x-apps/jx-app-athens:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/environment-controller:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/prow:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/dev-env:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/updatebot:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/ext-java-code-quality:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jx:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jx-docs:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jx-tutorial:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-builders-base-image:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-builders-base:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-builders:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-serverless-filerunner:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-serverless:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/homebrew-jx:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-image:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-platform:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
presubmits:
  jenkins-x/environment-tekton-mole-dev:
  - agent: tekton
    always_run: true
    context: promotion-build
    name: promotion-build
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
  jenkins-x/environment-tekton-mole-production:
  - agent: tekton
    always_run: true
    context: promotion-build
    name: promotion-build
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
  jenkins-x/environment-tekton-mole-staging:
  - agent: tekton
    always_run: true
    context: promotion-build
    name: promotion-build
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
  jenkins-x-apps/jx-app-athens:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/environment-controller:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/prow:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jx:
  - agent: tekton
    always_run: true
    context: bdd
    name: bdd
    rerun_command: /test bdd
    trigger: (?m)^/test( all| bdd),?(s+|$)
  - agent: tekton
    always_run: true
    context: integration
    name: integration
    rerun_command: /test integration
    trigger: (?m)^/test( all| integration),?(s+|$)
  - agent: tekton
    always_run: true
    context: lint
    name: lint
    rerun_command: /test lint
    trigger: (?m)^/test( all| lint),?(s+|$)
  jenkins-x/jx-docs:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jx-tutorial:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/dev-env:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test tekton
    trigger: (?m)^/test( all| tekton),?(s+|$)
  jenkins-x/updatebot:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test tekton
    trigger: (?m)^/test( all| tekton),?(s+|$)
  jenkins-x/ext-java-code-quality:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-builders-base-image:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-builders-base:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-builders:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-serverless-filerunner:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-serverless:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/homebrew-jx:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-image:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-platform:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
prowjob_namespace: jx
push_gateway: {}
sinker: {}
tide:
  context_options:
    from-branch-protection: true
    required-if-present-contexts: null
    skip-unknown-contexts: false
  queries:
  - labels:
    - approved
    - lgtm
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x/jx
    - jenkins-x/environment-tekton-mole-production
    - jenkins-x/environment-tekton-mole-staging
  - labels:
    - updatebot
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x-apps/jx-app-athens
    - jenkins-x-charts/environment-controller
    - jenkins-x-charts/prow
    - jenkins-x/jx-docs
    - jenkins-x/jx-tutorial
    - jenkins-x/jenkins-x-builders
    - jenkins-x/jenkins-x-builders-base
    - jenkins-x/jenkins-x-builders-base-image
    - jenkins-x/jenkins-x-serverless-filerunner
    - jenkins-x/jenkins-x-serverless
    - jenkins-x/homebrew-jx
    - jenkins-x/dev-env
    - jenkins-x/updatebot
    - jenkins-x/ext-java-code-quality
    - jenkins-x/jenkins-x-platform
    - jenkins-x/jenkins-x-image
  - labels:
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x-apps/jx-app-athens
    - jenkins-x-charts/environment-controller
    - jenkins-x-charts/prow
    - jenkins-x/jx-docs
    - jenkins-x/jx-tutorial
    - jenkins-x/jenkins-x-builders
    - jenkins-x/jenkins-x-builders-base
    - jenkins-x/jenkins-x-builders-base-image
    - jenkins-x/jenkins-x-serverless-filerunner
    - jenkins-x/jenkins-x-serverless
    - jenkins-x/homebrew-jx
    - jenkins-x/dev-env
    - jenkins-x/updatebot
    - jenkins-x/ext-java-code-quality
    - jenkins-x/jenkins-x-platform
    - jenkins-x/jenkins-x-image
    - jenkins-x/environment-tekton-mole-dev
  target_url: https://deck.infra.jrawlings.co.uk
