approve:
- lgtm_acts_as_approve: true
  require_self_approval: true
  repos:
  - jenkins-x
  - jenkins-x-charts
  - jenkins-x-apps
  - jenkinsci
  - cloudbees
blunderbuss: {}
cat: {}
lgtm:
- repos:
  - jenkins-x/jx
  review_acts_as_lgtm: true
- repos:
  - jenkinsci/jx-resources-plugin
  review_acts_as_lgtm: true
- repos:
  - cloudbees/core-backend
  review_acts_as_lgtm: true
- repos:
  - cloudbees/core-controller
  review_acts_as_lgtm: true
cherry_pick_unapproved: {}
config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
external_plugins:
  jenkins-x/environment-tekton-mole-dev: null
  jenkins-x/environment-tekton-mole-production: null
  jenkins-x/environment-tekton-mole-staging: null
heart:
  adorees:
  - jenkins-x-bot
owners: {}
plugins:
  jenkins-x/prow-config-tekton:
  - config-updater
  - size
  - shrug
  - skip
  - yuks
  jenkins-x/environment-tekton-mole-dev:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x/environment-tekton-mole-production:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x/environment-tekton-mole-staging:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x-apps/jx-app-athens:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/environment-controller:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/prow:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-builders:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-builders-base:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jx-docs:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jx-tutorial:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-builders-base-image:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-serverless-filerunner:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-serverless:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/dev-env:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/updatebot:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/ext-java-code-quality:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/homebrew-jx:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-platform:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jx:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
requiresig: {}
sigmention: {}
slack: {}
triggers:
- repos:
  - jenkins-x
  - jenkins-x-apps
  - jenkins-x-charts
  trusted_org: jenkins-x
  only_org_members: true
welcome:
- message_template: Welcome contributor to Jenkins X
