approve:
- lgtm_acts_as_approve: true
  require_self_approval: true
  repos:
  - jenkins-x/environment-tekton-mole-production
  - jenkins-x/environment-tekton-mole-staging
  - jenkins-x/environment-tekton-mole-dev
  - jenkins-x-charts/prow
  - jenkins-x/jx
  - jenkins-x/jenkins-x-builders-base-image
blunderbuss: {}
cat: {}
cherry_pick_unapproved: {}
config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
external_plugins:
  jenkins-x/environment-tekton-mole-dev: null
  jenkins-x/environment-tekton-mole-production: null
  jenkins-x/environment-tekton-mole-staging: null
heart: {}
owners: {}
plugins:
  jenkins-x/prow-config-tekton:
  - config-updater
  - size
  - shrug
  - skip
  - yuks
  jenkins-x/environment-tekton-mole-dev:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x/environment-tekton-mole-production:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x/environment-tekton-mole-staging:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x-charts/prow:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-builders-base-image:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jx:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
requiresig: {}
sigmention: {}
slack: {}
triggers:
- repos:
  - jenkins-x/environment-tekton-mole-production
  - jenkins-x/environment-tekton-mole-staging
  - jenkins-x/environment-tekton-mole-dev
  - jenkins-x-charts/prow
  - jenkins-x/jx
  - jenkins-x/jenkins-x-builders-base-image
  trusted_org: jenkins-x
  only_org_members: true
welcome:
- message_template: Welcome